// The agent path, end to end, with the fake `claude` CLI (test/fixtures/fake-claude) standing in
// for the real one. filos.claude.path points at it (runE2E writes the user settings). The tests
// run in the extension host itself, and the provider builds the CLI's environment from
// process.env at spawn time, so switching FAKE_CLAUDE_MODE here takes effect on the next run:
// no mode file or wrapper script is needed.

import * as assert from 'node:assert/strict';
import * as vscode from 'vscode';
import type { Workbench } from './cdp';
import { graphSettled } from './clicks.test';
import { cdpPort, filos, renderedAfter, shot, sleep, waitFor, workbench } from './helpers';

type Mode = 'ok' | 'auth' | 'contract' | 'budget' | 'slow' | 'crash' | 'fenced' | 'badtools';

function setMode(mode: Mode): void {
  process.env.FAKE_CLAUDE_MODE = mode;
}

export interface ErrorShown {
  message: string;
  actions: [string, string][];
  detail: string;
}

/** The error view as the webview draws it, once it is up. */
export function errorShown(wb: Workbench): Promise<ErrorShown> {
  return wb.waitForWebview<ErrorShown>(
    `(d) => {
      const e = d.querySelector('.status-host:not([hidden]) .status--error');
      if (!e) return null;
      return {
        message: e.querySelector('.status-message')?.textContent ?? '',
        actions: [...e.querySelectorAll('button[data-action]')].map((b) => [b.dataset.action, b.textContent]),
        detail: e.querySelector('.status-details pre')?.textContent ?? '',
      };
    }`,
    'the error view',
    10_000,
  );
}

export function registerAgentTests(): void {
  describe('Agent path (fake claude CLI)', function () {
    let wb: Workbench | undefined;

    before(async function () {
      const fake = process.env.FILOS_E2E_FAKE_CLAUDE;
      if (!fake) this.skip();
      assert.equal(vscode.workspace.getConfiguration('filos').get('claude.path'), fake, 'filos.claude.path should point at the fake CLI');
      if (cdpPort()) wb = await workbench();
    });

    after(() => setMode('ok'));

    it('Review Sample PR with Agent loads the graph the CLI returns, marked as agent output', async () => {
      const api = await filos();
      setMode('ok');
      const t0 = Date.now();
      await vscode.commands.executeCommand('filos.reviewSampleWithAgent');
      const s = api.getSession();
      assert.ok(s);
      assert.deepEqual(s.status, { kind: 'loaded' });
      assert.equal(s.source, 'agent');
      assert.equal(s.target.kind, 'sample');
      const r = await renderedAfter(t0, (x) => x.visibleNodes.length > 0, 20_000);
      assert.ok(r.visibleNodes.includes('money'));
      if (wb) {
        await graphSettled(wb);
        const badge = await wb.evalWebview<string>(`(d) => d.querySelector('.source-badge')?.textContent ?? ''`);
        assert.match(badge, /^Generated by claude/);
        await shot('agent-ok');
      }
      // Selecting still opens and folds code from the sample repo.
      await api.simulateSelect('money/Money.multiply');
      assert.equal(api.getCodePane().file, 'src/money/money.ts');
      assert.ok(api.getCodePane().foldVerified);
    });

    it('an expired login shows the error with "Log in again", which opens a login terminal; "Show sample instead" recovers', async function () {
      const api = await filos();
      setMode('auth');
      await vscode.commands.executeCommand('filos.reviewSampleWithAgent');
      const s = api.getSession();
      assert.ok(s);
      assert.equal(s.status.kind, 'error');
      assert.ok(s.status.kind === 'error');
      assert.equal(s.status.message, 'Your Claude Code session has expired.');
      assert.deepEqual(s.status.actions, ['login', 'retry', 'useFixture']);
      assert.match(s.status.detail ?? '', /auth login/);

      if (!wb) {
        await api.simulateAction('login');
        assert.ok(vscode.window.terminals.some((t) => t.name === 'Filos: Claude Code login'));
        return;
      }
      const shown = await errorShown(wb);
      assert.equal(shown.message, 'Your Claude Code session has expired.');
      assert.deepEqual(shown.actions, [
        ['login', 'Log in again'],
        ['retry', 'Retry'],
        ['useFixture', 'Show sample instead'],
      ]);
      await shot('agent-auth-error');

      await wb.clickWebview('button[data-action="login"]');
      const terminal = await waitFor(() => vscode.window.terminals.find((t) => t.name === 'Filos: Claude Code login'), 'the "Filos: Claude Code login" terminal');
      await sleep(500);
      await shot('agent-login-terminal');
      terminal.dispose();

      setMode('ok');
      const t = Date.now();
      await wb.clickWebview('button[data-action="useFixture"]');
      await waitFor(() => {
        const x = api.getSession();
        return x?.status.kind === 'loaded' && x.source === 'fixture';
      }, 'the sample to load');
      await renderedAfter(t, (x) => x.visibleNodes.length > 0);
    });

    it('a graph that breaks the contract shows the validation errors; Retry runs the agent again', async function () {
      const api = await filos();
      setMode('contract');
      await vscode.commands.executeCommand('filos.reviewSampleWithAgent');
      const s = api.getSession();
      assert.ok(s?.status.kind === 'error', `expected an error, got ${JSON.stringify(s?.status)}`);
      assert.equal(s.status.message, "The agent's answer didn't match the review-graph contract.");
      assert.deepEqual(s.status.actions, ['retry', 'useFixture']);
      // The fake adds an edge to a node that doesn't exist and an anchor past the end of a file.
      assert.match(s.status.detail ?? '', /ceilToCents/);

      if (!wb) return;
      const shown = await errorShown(wb);
      assert.equal(shown.message, s.status.message);
      assert.deepEqual(shown.actions.map(([a]) => a), ['retry', 'useFixture']);
      assert.match(shown.detail, /ceilToCents/);
      await wb.clickWebview('.status-details summary');
      assert.ok(await wb.waitForWebview<boolean>(`(d) => d.querySelector('.status-details')?.open === true`, 'the details to open'));
      await shot('agent-contract-error');

      setMode('ok');
      const t = Date.now();
      await wb.clickWebview('button[data-action="retry"]');
      await waitFor(() => {
        const x = api.getSession();
        return x?.status.kind === 'loaded' && x.source === 'agent';
      }, 'the retried agent run to load', 20_000);
      await renderedAfter(t, (x) => x.visibleNodes.length > 0);
    });

    it('"Re-run analysis" runs the agent again on the PR being shown', async function () {
      if (!wb) this.skip();
      const api = await filos();
      await graphSettled(wb);
      // A failing mode makes the re-run visible: the graph gives way to the error view.
      setMode('budget');
      await wb.clickWebview('.toolbar button', { text: 'Re-run analysis' });
      await waitFor(() => api.getSession()?.status.kind === 'error', 'the re-run to finish with the budget error', 20_000);
      const shown = await errorShown(wb);
      assert.match(shown.message, /spending cap/);

      setMode('ok');
      await wb.clickWebview('button[data-action="useFixture"]');
      await waitFor(() => {
        const x = api.getSession();
        return x?.status.kind === 'loaded' && x.source === 'fixture';
      }, 'the sample to load');
    });
  });
}
